on: 
  push: 
    branches:
      - main

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Atualizar Data do Commit
      run: |
        DATA_COMMIT=$(date +"%d/%m/%Y %H:%M:%S")
        sed -i "s/<!--DATA_COMMIT-->/$DATA_COMMIT/" index.html

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: public_html/
